apiVersion: v1
kind: Secret
metadata:
  name: alchemist-secrets
  namespace: alchemist
type: Opaque
stringData:
  ENCRYPTION_KEY: "cAif1G2PwVSv5KYqYJUE1KZrAjlTmWDNVBY6l21ktq4=" # CHANGE KEY BEFORE PRODUCTION !!!
  SECRET_KEY: "django-secret-key"
  REDIS_URL: "redis://redis:6379/1"
  POSTGRES_PASSWORD: "postgres_pass"
  DB_PASS: "postgres_pass"
